export interface MedicalAnalysisPromptOptions {
  patientName?: string;
  cancerType?: string;
  cancerStage?: string;
  userContext?: Record<string, unknown> | null;
}

export interface NarrativeMedicalAnalysis {
  disclaimer: string;
  keyFindings: string[];
  analysisBreakdown: string[];
  treatmentConsiderations: string[];
  symptomManagement: string[];
  nextSteps: string[];
  encouragement?: string;
}

export const DISCLAIMER_TEXT = "This analysis is generated by an AI assistant to help you understand your medical records. It is for informational purposes only and MUST be discussed with your qualified healthcare team. This is not medical advice, diagnosis, or treatment recommendation.";

export const getMedicalAnalysisPrompt = (
  medicalRecordText: string,
  options: MedicalAnalysisPromptOptions = {}
) => {
  const contextLines: string[] = [];

  if (options.patientName) {
    contextLines.push(`Patient Name: ${options.patientName}`);
  }
  if (options.cancerType) {
    contextLines.push(`Cancer Type: ${options.cancerType}`);
  }
  if (options.cancerStage) {
    contextLines.push(`Cancer Stage: ${options.cancerStage}`);
  }
  if (options.userContext) {
    contextLines.push(`Additional Context: ${JSON.stringify(options.userContext)}`);
  }

  const contextBlock = contextLines.length
    ? `PATIENT CONTEXT\n${contextLines.join('\n')}`
    : `PATIENT CONTEXT\nNot provided; infer only from the document contents.`;

  return `You are a specialized oncology nurse navigator who explains medical findings in clear, compassionate language. Analyze the provided medical record and respond **only** with valid JSON that follows this schema:
{
  "disclaimer": "${DISCLAIMER_TEXT}",
  "keyFindings": ["Short executive summary sentences in plain language"],
  "analysisBreakdown": ["Paragraph 1 that explains the results in context", "Paragraph 2..."],
  "treatmentConsiderations": ["Discussion points for the care team written as sentences or short paragraphs"],
  "symptomManagement": ["Guidance on side effects and when to call the care team"],
  "nextSteps": ["Practical preparation tips and upcoming milestones"],
  "encouragement": "One short supportive closing sentence"
}

Requirements:
- Always include the medical disclaimer exactly as written.
- Provide 3-5 key findings.
- analysisBreakdown must contain 2-3 full paragraphs (as strings) that explain results in everyday language and define medical terms.
- Use sentences/paragraphs instead of bullet points for all list entries. Separate different ideas into different array items.
- Frame treatment considerations as "discussion points" rather than direct medical advice.
- Encourage patients to collaborate with their oncology team and explain any technical words in parentheses the first time they appear.
- Maintain a hopeful, empowering tone without minimizing clinical realities.

${contextBlock}

MEDICAL RECORD CONTENT
${medicalRecordText}`;
};

export const getNarrativeMockAnalysis = (): NarrativeMedicalAnalysis => ({
  disclaimer: DISCLAIMER_TEXT,
  keyFindings: [
    'No AI key findings available yet; this is a placeholder summary.',
    'Upload a detailed pathology, imaging, or lab report to receive tailored insights.'
  ],
  analysisBreakdown: [
    'We could not read the full medical record text, so this summary is limited. Once the document text is available, the AI will explain the findings in clear, patient-friendly language.',
    'Please discuss your medical situation directly with your oncology care team for personalized recommendations.'
  ],
  treatmentConsiderations: [
    'Ask your oncologist to walk through the goals of your current treatment plan and confirm whether any adjustments are needed based on recent results.'
  ],
  symptomManagement: [
    'Track any new or worsening symptoms, including pain, fatigue, or shortness of breath, and alert your healthcare team if they persist or become severe.'
  ],
  nextSteps: [
    'Prepare for your next visit by noting key questions and bringing copies of imaging or lab reports for reference.'
  ],
  encouragement: 'You are taking an important step by organizing your medical records—keep partnering with your care team.'
});
